Split big test cases

diff --git a/lib/mockframework b/lib/mockframework
--- a/lib/mockframework
+++ b/lib/mockframework
@@ -8,13 +8,21 @@ fi
 shopt -s expand_aliases
 export PATH_ORIGIN="$PATH"
 
-if [[ "${BESTING_DEBUG:-}" == true ]]; then
-    eval "$(type debug | command sed -e 1d -e 's, 1\?>\&2 8> /dev/null, >\&8,' -e 's/ 1\?>\&2//')"
-    exec 8>&2
-else
+if [[ "${BESTING_DEBUG:-}" != true ]]; then
     function debug() {
         :
     }
+else
+    exec 8>&2
+    function debug() {
+        if [[ "$#" -gt 0 ]]; then
+            out "[DEBUG]" "$@"
+        else
+            while IFS='\n' read -r line; do
+                printf "[DEBUG] %s\n" "$line"
+            done
+        fi
+    } >&8
 fi
 
 function besting-real-command() {
@@ -33,12 +41,12 @@ function besting-run-tests() {
     declare -i total=0 error=0
     while read -r _ _ name; do
         [[ "$name" == *"-assert" ]] && continue
-        debug "Running test: $name"
+        #debug "Running test: $name"
         : $(( total++ ))
         assert-execution "$name" || true : $(( error++ ))
     done < <(besting-run-tests--get-all-tests)
 
-    printf "\n-----\nAll tests: %s, Failed tests: %d\n" "$total" "$error" >&2
+    printf -- "-----\nAll tests: %s, failed: %d\n" "$total" "$error" >&2
 }
 
 function besting-on-exit() {
@@ -99,22 +107,6 @@ function mock-command() {
 }
 alias @mock="mock-command"
 
-function command_not_found_handle() {
-    declare mockfunc name="$1"
-    mockfunc="mock_exec_${name}_$(builtin echo -n "$@" | gmd5sum | /usr/bin/cut -b1-32)"
-    # debug "mockid=$mockid" >&2
-    if [[ "$(type -t "${mockfunc}")" == function ]]; then
-        "${mockfunc}" "$@"
-    elif [[ "$(type -t "${name}")" == function ]]; then
-        debug "[CNFH-builtin]" "$@"
-        builtin "$@"
-    else
-        debug "[CNFH-default]" "$@"
-        builtin echo "$@"
-    fi
-} 8>/dev/null
-export -f command_not_found_handle
-
 function mock-all-commands() {
     declare name body
     for name; do
@@ -128,26 +120,52 @@ alias @setup='function besting_framework_setup'
 
 @mockall cd
 
+declare -xa BESTING_ASSERT_DIFF_OPTS=(-w -C3)
 function assert-execution() (
-    PATH=path-not-exists
-    declare name="$1"
-    if /usr/bin/diff -w -C3  <(
+    declare name="$1" tmpdir testresult
+    tmpdir="$(@real mktemp -d)"
+    testresult="$(@real mktemp)"
+    #trap '/bin/rm -vrf "$tmpdir" "$testresult"' RETURN
+    pushd "$tmpdir" &>/dev/null
+    declare retval=1
+
+    function command_not_found_handle() {
+        declare mockfunc name="$1"
+        mockfunc="mock_exec_${name}_$(builtin echo -n "$@" | gmd5sum | /usr/bin/cut -b1-32)"
+        # debug "mockid=$mockid" >&2
+        if [[ "$(type -t "${mockfunc}")" == function ]]; then
+            debug "[CNFH-func]" "${mockfunc}" "$@"
+            "${mockfunc}" "$@"
+        elif [[ "$(type -t "${name}")" == function ]]; then
+            debug "[CNFH-builtin]" "$@"
+            builtin "$@"
+        else
+            debug "[CNFH-default]" "$@"
+            builtin echo "$@"
+        fi
+    } #8>/dev/null
+    export -f command_not_found_handle
+    export PATH=path-not-exists
+
+    if @real diff "${BESTING_ASSERT_DIFF_OPTS[@]}" <(
             set +eu
-            shopt -s restricted_shell
             "${name}"-assert
         ) <(
             set +eu
-            shopt -s restricted_shell
             [[ "$(builtin type -t besting_framework_setup)" == function ]] && besting_framework_setup
             "${name}"
-        )
+        ) &>"$testresult" 8>&2
     then
         printf "\e[1;36m[PASS] %s\e[0;m\n" "$name"
-        return 0
+        retval=0
     else
         printf "\e[1;31m[FAIL] %s\e[0;m\n" "$name"
-        return 1
+        @real cat "$testresult" 2>/dev/null 8>/dev/null
+        printf "\n"
     fi
+    pushd &>/dev/null
+    @real rm -rf "$tmpdir" "$testresult"
+    return "$retval"
 )
 
 function ignore-command() {
