Allow to mock a script file

diff --git a/lib/mockframework b/lib/mockframework
--- a/lib/mockframework
+++ b/lib/mockframework
@@ -35,16 +35,21 @@ for name in cd command echo eval exec false popd pushd pwd true type; do
     eval "function _${name}() { builtin $name \"\$@\"; } 8>/dev/null; export -f _${name}"
 done
 
-for name in echo test; do
+for name in echo pwd test; do
     declare -grx "_${name}"="$(besting-real-path "$name")"
 done
 
-for name in cat cut diff grep md5sum mktemp rm sed which xargs; do
+for name in cat chmod cut diff find grep ls md5sum mktemp rm sed tee touch which xargs; do
     declare -grx "_${name}"="$(besting-real-path "$name")"
     eval "function _${name}() { \"\${_${name}}\" \"\$@\"; } 8>/dev/null; export -f _${name}"
 done
 
 function besting-real-command() {
+    declare name="$1"
+    if [[ "$name" == */* ]]; then
+        _echo "$@"
+        return
+    fi
     declare -a cmd
     cmd=("$(besting-real-path "$1")" "${@:2}")
     debug "[REAL-CMD]" "${cmd[@]}"
@@ -58,6 +63,7 @@ function besting-run-tests--get-all-tests() {
 }
 
 function besting-run-tests() {
+    set -euo pipefail
     declare -i total=0 error=0
     while read -r _ _ name; do
         [[ "$name" == *"-assert" ]] && continue
@@ -116,17 +122,30 @@ function @mock() {
         [[ "$param" == '--' ]] && break
         cmd+=("$param")
     done
-    declare mockfunc
-    mockfunc="mock_exec_${name}_$(_echo -n "${cmd[@]}" | _md5sum | _cut -b1-32)"
-    #stderr name="$name"
-    if [[ "$#" -gt 0 ]]; then
-        func="$*"
+    if [[ "$name" == /* ]]; then
+        die "Cannot mock an absolute path: $name"
+    elif [[ "$name" == */* ]] && [[ -e "$name" ]]; then
+        die "Cannot mock an existed path: $name"
+    elif [[ "$name" == */* ]]; then
+        [[ -d "${name%/*}" ]] || mkdir -p "${name%/*}"
+        _cat > "$name" <<SCRIPT
+#!/bin/bash
+${_echo} "$name" "\$@"
+SCRIPT
+        _chmod +x "$name" >&2
     else
-        func="$(_cat)"
+        declare mockfunc
+        mockfunc="mock_exec_${name}_$(_echo -n "${cmd[@]}" | _md5sum | _cut -b1-32)"
+        #stderr name="$name"
+        if [[ "$#" -gt 0 ]]; then
+            func="$*"
+        else
+            func="$(_cat)"
+        fi
+        body="function ${mockfunc}() { debug Running mock : '${cmd[*]}' :; $func; }"
+        # debug "$body"
+        eval "$body"
     fi
-    body="function ${mockfunc}() { debug Running mock : '${cmd[*]}' :; $func; }"
-    # debug "$body"
-    eval "$body"
 }
 export -f @mock
 
