Mock script file

diff --git a/lib/mockframework b/lib/mockframework
--- a/lib/mockframework
+++ b/lib/mockframework
@@ -59,21 +59,26 @@ export -f besting-real-command
 alias @real=besting-real-command
 
 function besting-run-tests--get-all-tests() {
-    declare -F | "$@grep" 'declare -f test.\+'
+    declare -F | while read -r _ _ name; do
+        [[ "$name" == test?* ]] || continue
+        [[ "$name" == *-assert ]] && continue
+        printf "%s\n" "$name"
+    done
 }
 
 function besting-run-tests() {
     set -euo pipefail
     declare -i total=0 error=0
-    while read -r _ _ name; do
-        [[ "$name" == *"-assert" ]] && continue
-        #debug "Running test: $name"
+    declare -a all_tests
+    mapfile -t all_tests < <(besting-run-tests--get-all-tests)
+    for name in "${all_tests[@]}"; do
+        # debug "Running test: $name"
         : $(( total++ ))
         assert-execution "$name" || true : $(( error++ ))
-    done < <(besting-run-tests--get-all-tests)
+    done
 
-    printf -- "-----\nAll tests: %s, failed: %d\n" "$total" "$error" >&2
-    [[ "$error" == 0 ]]
+    printf -- "-----\nAll tests: %s, failed: %d, skipped: %d\n" "$total" "$error" "$(( ${#all_tests[@]} - $total ))">&2
+    [[ "$error" == 0 ]] && [[ "${#all_tests[@]}" -eq "$total" ]]
 }
 
 function besting-on-exit() {
@@ -126,22 +131,29 @@ function @mock() {
         die "Cannot mock an absolute path: $name"
     elif [[ "$name" == */* ]] && [[ -e "$name" ]]; then
         die "Cannot mock an existed path: $name"
-    elif [[ "$name" == */* ]]; then
+    fi
+    debug "@mock $name"
+    if [[ "$#" -gt 0 ]]; then
+        debug "@mock $name $*"
+        func="$*"
+    elif [[ ! -t 0 ]]; then
+        debug "@mock $name @cat"
+        func="$(@cat)"
+    else
+        debug "@mock $name $_echo"
+        func="${_echo} \"${name}\" \"\$@\""
+    fi
+    if [[ "$name" == */* ]]; then
         [[ -d "${name%/*}" ]] || @mkdir -p "${name%/*}"
         @cat > "$name" <<SCRIPT
 #!/bin/bash
-${_echo} "$name" "\$@"
+${func}
 SCRIPT
         @chmod +x "$name" >&2
     else
         declare mockfunc
         mockfunc="mock_exec_${name}_$(@echo -n "${cmd[@]}" | @md5sum | @cut -b1-32)"
         #stderr name="$name"
-        if [[ "$#" -gt 0 ]]; then
-            func="$*"
-        else
-            func="$(@cat)"
-        fi
         body="function ${mockfunc}() { debug Running mock : '${cmd[*]}' :; $func; }"
         # debug "$body"
         eval "$body"
